CREATE OR REPLACE FUNCTION GET_PROFIT (
    INPUT_ID INT
) RETURN VARCHAR2 AS
    INITIAL_BALANCE NUMERIC(10, 2);
    GRACE           INT;
    FINAL_BALANCE   NUMERIC(10, 2);
    PROFIT          NUMERIC(10, 2);
    RATE            NUMERIC(10, 2);
    BEGIN_DATE      DATE;
    CURR_DATE       DATE;
    MONTH           INT;
    CO              INT;
    TOTAL_PROFIT    NUMERIC(10, 2);
    OUTPUT          VARCHAR2(1000);
BEGIN
 -- FETCHING BALANCE
    SELECT
        PRINCIPAL_AMOUNT INTO INITIAL_BALANCE
    FROM
        BALANCE
    WHERE
        A_ID = INPUT_ID;
 -- FETCHING PROFIT
    SELECT
        PROFIT INTO PROFIT
    FROM
        BALANCE
    WHERE
        A_ID = INPUT_ID;
 -- FETCHING GRACE
    SELECT
        ACCOUNT_PROPERTY.AP_GRACE_PERIOD INTO GRACE
    FROM
        ACCOUNT_PROPERTY,
        ACCOUNT
    WHERE
        ACCOUNT_PROPERTY.AP_ID = ACCOUNT.A_CODE
        AND ACCOUNT.A_ID = INPUT_ID;
 -- FETCHING RATE
    SELECT
        ACCOUNT_PROPERTY.AP_PROFIT_RATE INTO RATE
    FROM
        ACCOUNT_PROPERTY,
        ACCOUNT
    WHERE
        ACCOUNT_PROPERTY.AP_ID = ACCOUNT.A_CODE
        AND ACCOUNT.A_ID = INPUT_ID;
 -- FETCHING LAST DATE
    SELECT
        LAST_DATE_INTEREST INTO BEGIN_DATE
    FROM
        ACCOUNT
    WHERE
        A_ID = INPUT_ID;
 -- FETCHING CURRENT DATE
    SELECT
        TO_DATE(CURRENT_DATE) INTO CURR_DATE
    FROM
        DUAL;
 -- MONTH := TRUNC(SELECT MONTHS_BETWEEN (CURR_DATE,BEGIN_DATE) "Months"
 --                 FROM DUAL);
    MONTH:= TRUNC(MONTHS_BETWEEN(SYSDATE, BEGIN_DATE));
    CO := 1;
    TOTAL_PROFIT :=0;
    FINAL_BALANCE:=INITIAL_BALANCE;
    FOR I IN 1..MONTH LOOP
        IF CO !=GRACE THEN
            PROFIT := PROFIT+FINAL_BALANCE*RATE;
        ELSIF CO = GRACE THEN
            FINAL_BALANCE := FINAL_BALANCE + PROFIT;
            TOTAL_PROFIT := TOTAL_PROFIT + PROFIT;
            PROFIT := 0;
            CO := 0;
        END IF;
        CO := CO+1;
    END LOOP;
    TOTAL_PROFIT := TOTAL_PROFIT + PROFIT;
    OUTPUT := 'THE ACC NO '
        || INPUT_ID
        || ' BALANCE BEFORE PROFIT WAS '
        || INITIAL_BALANCE
        || ' . AND NOW THE BALANCE AFTER PROFIT IS '
        || FINAL_BALANCE
        || ' WITH TOTAL PROFIT BEING '
        || TOTAL_PROFIT;
    RETURN OUTPUT;
END;
/

DECLARE
    ID INT;
BEGIN
    ID:='&ID';
    DBMS_OUTPUT.PUT_LINE(GET_PROFIT(ID));
END;
/